### ISSUE TITLE
Shape Mismatch Error on predict

### ISSUE THREAD

**Issue by peroon** [peroon/deepanalytics_food_classification#2]
動作再現を試していただいた方から、Predict時に以下のエラーで止まるとのフィードバックを頂いた。

```
学習済みモデルをDL resnext-101
[10:32:50] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[10:32:50] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
予測します fold i 0 crop i 0
[10:32:50] src/io/iter_image_recordio_2.cc:135: ImageRecordIOParser2: /home2/challenge48/classification/peroon/data/mxnet/test_224x224_crop_0.rec, use 4 threads for decoding..
[10:32:55] src/operator/././cudnn_algoreg-inl.h:57: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[10:32:59] /home2/challenge48/mxnet/dmlc-core/include/dmlc/./logging.h:300: [10:32:59] src/ndarray/ndarray.cc:239: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (256,1024,1,1) to.shape=(512,1024,1,1)

Stack trace returned 10 entries:
[bt] (0) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f7cd061219c]
[bt] (1) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet10CopyFromToERKNS_7NDArrayEPS0_i+0x536) [0x7f7cd0f37a06]
[bt] (2) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(+0xe1ff6a) [0x7f7cd0ec3f6a]
[bt] (3) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(MXImperativeInvoke+0x501) [0x7f7cd124f471]
[bt] (4) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f7cdd62ee20]
[bt] (5) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x2eb) [0x7f7cdd62e88b]
[bt] (6) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x49a) [0x7f7cdd62901a]
[bt] (7) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(+0x9fcb) [0x7f7cdd61cfcb]
[bt] (8) python3(PyObject_Call+0x47) [0x5b7167]
[bt] (9) python3(PyEval_EvalFrameEx+0x4f06) [0x528d06]

Traceback (most recent call last):
  File "dmlc_mxnet/example/image-classification/fine-tune.py", line 189, in <module>
    fine_tune(mode='predict')
  File "dmlc_mxnet/example/image-classification/fine-tune.py", line 157, in fine_tune
    mod.load_params('temp/model_weight/{}/model_params_fold_i_{}'.format(MODEL_NAME, fold_i))
  File "/home2/challenge48/mxnet/python/mxnet/module/base_module.py", line 672, in load_params
    self.set_params(arg_params, aux_params)
  File "/home2/challenge48/mxnet/python/mxnet/module/module.py", line 309, in set_params
    allow_missing=allow_missing, force_init=force_init)
  File "/home2/challenge48/mxnet/python/mxnet/module/module.py", line 273, in init_params
    _impl(desc, arr, arg_params)
  File "/home2/challenge48/mxnet/python/mxnet/module/module.py", line 261, in _impl
    cache_arr.copyto(arr)
  File "/home2/challenge48/mxnet/python/mxnet/ndarray.py", line 819, in copyto
    return _internal._copyto(self, out=other)
  File "/home2/challenge48/mxnet/python/mxnet/_ctypes/ndarray.py", line 164, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(val) for val in vals])))
  File "/home2/challenge48/mxnet/python/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:32:59] src/ndarray/ndarray.cc:239: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (256,1024,1,1) to.shape=(512,1024,1,1)

Stack trace returned 10 entries:
[bt] (0) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f7cd061219c]
[bt] (1) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet10CopyFromToERKNS_7NDArrayEPS0_i+0x536) [0x7f7cd0f37a06]
[bt] (2) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(+0xe1ff6a) [0x7f7cd0ec3f6a]
[bt] (3) /home2/challenge48/mxnet/python/mxnet/../../lib/libmxnet.so(MXImperativeInvoke+0x501) [0x7f7cd124f471]
[bt] (4) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f7cdd62ee20]
[bt] (5) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x2eb) [0x7f7cdd62e88b]
[bt] (6) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x49a) [0x7f7cdd62901a]
[bt] (7) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(+0x9fcb) [0x7f7cdd61cfcb]
[bt] (8) python3(PyObject_Call+0x47) [0x5b7167]
[bt] (9) python3(PyEval_EvalFrameEx+0x4f06) [0x528d06]
```

**Comment by peroon** [comment]
現象が再現できた。

公開している訓練済みモデルは訓練に2日以上かかるので、
今回のfine-tune.pyで生成されたものではなく、
もっとごちゃごちゃしたコード環境で生成されたものを代わりにUPしていた。

訓練コードは同じなので、動くと思ったのだが動かなかった。
整理して書き直しているときにパラメータの何処かにズレがあったのだろう。

今回のfine-tune.pyでPredictするときに、公開している訓練済みモデルを読ませると上記エラーが
発生した。fine-tune.pyで生成した訓練済みモデルを使用すれば正常に動くことを確認した。

正常に動く訓練済みモデルをUPし直す。

**Comment by peroon** [comment]
＞もっとごちゃごちゃしたコード環境で生成されたもの
223MB

＞今回のfine-tune.pyで生成されたもの
161MB

サイズが違う・・・。
動くけど、精度が0.82と同じものが出せるか保証できない・・・。

**Comment by peroon** [comment]
最終予測したラベルリストが同じならいいのでは？

223MBで予測した記録が残っていたので、今回の161MBで予測したものと比較した。
最終予測はかなり違った。

223MBの重みを出力するようにコードを修正するのがよさそう。
（ということは訓練もし直しか・・・）

**Comment by peroon** [comment]
整理前のコードではresnext以外でもいろいろ試していて
ifで切り替えていたがミスでどれも

```
get_model('http://data.mxnet.io/models/imagenet-11k/resnet-152/resnet-152', 0)
sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-152', 0)
```

これを使うようになっていて、それで作られたモデルが223MB.
正しくresnextを指定すると161MBが出力される。
resnet-152は名前からして層が多いので223MBになっているのも納得できる。

161MBの訓練済みモデルをUPして正常動作することを確認していただく。
